FROM registry.redhat.io/rhel9/rhel-bootc:9.5

#install the missing php components
RUN dnf module enable -y php:8.2 nginx:1.22 && dnf install -y httpd  php-fpm && dnf clean all

#start the services automatically on boot
RUN systemctl enable httpd php-fpm